[package]
name = "rusty_rogues"
version = "0.2.0"
authors = ["TheFirstLairron"]
edition = "2021"

[dependencies]
tcod = { version = "0.12", features = ["serialization"] }
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"